// Copyright (c) 2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: service.proto

package serviceextension

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateVivoxTokenRequestType int32

const (
	GenerateVivoxTokenRequestType_generatevivoxtokenrequest_type_unknown GenerateVivoxTokenRequestType = 0
	GenerateVivoxTokenRequestType_login                                  GenerateVivoxTokenRequestType = 1
	GenerateVivoxTokenRequestType_join                                   GenerateVivoxTokenRequestType = 2
	GenerateVivoxTokenRequestType_join_muted                             GenerateVivoxTokenRequestType = 3
	GenerateVivoxTokenRequestType_kick                                   GenerateVivoxTokenRequestType = 4
)

// Enum value maps for GenerateVivoxTokenRequestType.
var (
	GenerateVivoxTokenRequestType_name = map[int32]string{
		0: "generatevivoxtokenrequest_type_unknown",
		1: "login",
		2: "join",
		3: "join_muted",
		4: "kick",
	}
	GenerateVivoxTokenRequestType_value = map[string]int32{
		"generatevivoxtokenrequest_type_unknown": 0,
		"login":                                  1,
		"join":                                   2,
		"join_muted":                             3,
		"kick":                                   4,
	}
)

func (x GenerateVivoxTokenRequestType) Enum() *GenerateVivoxTokenRequestType {
	p := new(GenerateVivoxTokenRequestType)
	*p = x
	return p
}

func (x GenerateVivoxTokenRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerateVivoxTokenRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (GenerateVivoxTokenRequestType) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x GenerateVivoxTokenRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerateVivoxTokenRequestType.Descriptor instead.
func (GenerateVivoxTokenRequestType) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type GenerateVivoxTokenRequestChannelType int32

const (
	GenerateVivoxTokenRequestChannelType_generatevivoxtokenrequest_channeltype_unknown GenerateVivoxTokenRequestChannelType = 0
	GenerateVivoxTokenRequestChannelType_echo                                          GenerateVivoxTokenRequestChannelType = 1
	GenerateVivoxTokenRequestChannelType_positional                                    GenerateVivoxTokenRequestChannelType = 2
	GenerateVivoxTokenRequestChannelType_nonpositional                                 GenerateVivoxTokenRequestChannelType = 3
)

// Enum value maps for GenerateVivoxTokenRequestChannelType.
var (
	GenerateVivoxTokenRequestChannelType_name = map[int32]string{
		0: "generatevivoxtokenrequest_channeltype_unknown",
		1: "echo",
		2: "positional",
		3: "nonpositional",
	}
	GenerateVivoxTokenRequestChannelType_value = map[string]int32{
		"generatevivoxtokenrequest_channeltype_unknown": 0,
		"echo":          1,
		"positional":    2,
		"nonpositional": 3,
	}
)

func (x GenerateVivoxTokenRequestChannelType) Enum() *GenerateVivoxTokenRequestChannelType {
	p := new(GenerateVivoxTokenRequestChannelType)
	*p = x
	return p
}

func (x GenerateVivoxTokenRequestChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerateVivoxTokenRequestChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[1].Descriptor()
}

func (GenerateVivoxTokenRequestChannelType) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[1]
}

func (x GenerateVivoxTokenRequestChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerateVivoxTokenRequestChannelType.Descriptor instead.
func (GenerateVivoxTokenRequestChannelType) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

type GenerateVivoxTokenRequest struct {
	state          protoimpl.MessageState               `protogen:"open.v1"`
	Type           GenerateVivoxTokenRequestType        `protobuf:"varint,1,opt,name=type,proto3,enum=service.GenerateVivoxTokenRequestType" json:"type,omitempty"`
	Username       string                               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ChannelId      string                               `protobuf:"bytes,3,opt,name=channelId,proto3" json:"channelId,omitempty"`
	ChannelType    GenerateVivoxTokenRequestChannelType `protobuf:"varint,4,opt,name=channelType,proto3,enum=service.GenerateVivoxTokenRequestChannelType" json:"channelType,omitempty"`
	TargetUsername string                               `protobuf:"bytes,5,opt,name=targetUsername,proto3" json:"targetUsername,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateVivoxTokenRequest) Reset() {
	*x = GenerateVivoxTokenRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateVivoxTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateVivoxTokenRequest) ProtoMessage() {}

func (x *GenerateVivoxTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateVivoxTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateVivoxTokenRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateVivoxTokenRequest) GetType() GenerateVivoxTokenRequestType {
	if x != nil {
		return x.Type
	}
	return GenerateVivoxTokenRequestType_generatevivoxtokenrequest_type_unknown
}

func (x *GenerateVivoxTokenRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GenerateVivoxTokenRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *GenerateVivoxTokenRequest) GetChannelType() GenerateVivoxTokenRequestChannelType {
	if x != nil {
		return x.ChannelType
	}
	return GenerateVivoxTokenRequestChannelType_generatevivoxtokenrequest_channeltype_unknown
}

func (x *GenerateVivoxTokenRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

type GenerateVivoxTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateVivoxTokenResponse) Reset() {
	*x = GenerateVivoxTokenResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateVivoxTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateVivoxTokenResponse) ProtoMessage() {}

func (x *GenerateVivoxTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateVivoxTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateVivoxTokenResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateVivoxTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GenerateVivoxTokenResponse) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aservice\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x10permission.proto\"\x9b\x03\n" +
	"\x19GenerateVivoxTokenRequest\x12I\n" +
	"\x04type\x18\x01 \x01(\x0e2&.service.GenerateVivoxTokenRequestTypeB\r\x92A\n" +
	"2\bRequiredR\x04type\x12)\n" +
	"\busername\x18\x02 \x01(\tB\r\x92A\n" +
	"2\bRequiredR\busername\x12:\n" +
	"\tchannelId\x18\x03 \x01(\tB\x1c\x92A\x192\x17Required if type = joinR\tchannelId\x12m\n" +
	"\vchannelType\x18\x04 \x01(\x0e2-.service.GenerateVivoxTokenRequestChannelTypeB\x1c\x92A\x192\x17Required if type = joinR\vchannelType\x12D\n" +
	"\x0etargetUsername\x18\x05 \x01(\tB\x1c\x92A\x192\x17Required if type = kickR\x0etargetUsername:\x17\x92A\x14\n" +
	"\x12\xd2\x01\x04type\xd2\x01\busername\"P\n" +
	"\x1aGenerateVivoxTokenResponse\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri*z\n" +
	"\x1dGenerateVivoxTokenRequestType\x12*\n" +
	"&generatevivoxtokenrequest_type_unknown\x10\x00\x12\t\n" +
	"\x05login\x10\x01\x12\b\n" +
	"\x04join\x10\x02\x12\x0e\n" +
	"\n" +
	"join_muted\x10\x03\x12\b\n" +
	"\x04kick\x10\x04*\x86\x01\n" +
	"$GenerateVivoxTokenRequestChannelType\x121\n" +
	"-generatevivoxtokenrequest_channeltype_unknown\x10\x00\x12\b\n" +
	"\x04echo\x10\x01\x12\x0e\n" +
	"\n" +
	"positional\x10\x02\x12\x11\n" +
	"\rnonpositional\x10\x032\xa6\x01\n" +
	"\aService\x12\x9a\x01\n" +
	"\x12GenerateVivoxToken\x12\".service.GenerateVivoxTokenRequest\x1a#.service.GenerateVivoxTokenResponse\";\x92A$\x12\x14Generate Vivox tokenb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/tokenB\xbf\x01\x92AH\x12\x1b\n" +
	"\x14Vivox Authentication2\x031.0\"\b/serviceZ\x1f\n" +
	"\x1d\n" +
	"\x06Bearer\x12\x13\b\x02\x1a\rAuthorization \x02\n" +
	"%net.accelbyte.extend.serviceextensionP\x01Z%accelbyte.net/extend/serviceextension\xaa\x02!AccelByte.Extend.ServiceExtensionb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_proto_goTypes = []any{
	(GenerateVivoxTokenRequestType)(0),        // 0: service.GenerateVivoxTokenRequestType
	(GenerateVivoxTokenRequestChannelType)(0), // 1: service.GenerateVivoxTokenRequestChannelType
	(*GenerateVivoxTokenRequest)(nil),         // 2: service.GenerateVivoxTokenRequest
	(*GenerateVivoxTokenResponse)(nil),        // 3: service.GenerateVivoxTokenResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: service.GenerateVivoxTokenRequest.type:type_name -> service.GenerateVivoxTokenRequestType
	1, // 1: service.GenerateVivoxTokenRequest.channelType:type_name -> service.GenerateVivoxTokenRequestChannelType
	2, // 2: service.Service.GenerateVivoxToken:input_type -> service.GenerateVivoxTokenRequest
	3, // 3: service.Service.GenerateVivoxToken:output_type -> service.GenerateVivoxTokenResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_permission_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
